### ISSUE TITLE
Doesnt seem to build with templateUrl

### ISSUE THREAD

**Issue by VivekPMenon** [vsavkin/router_lazyloading#1]
Thanks much Victor for demonstrating the concept in such a simple app like this. 

Looks like the sample doesn't build if external templates are used. I know it may be out of scope as far as this repo is concerned. If you don't mind, Can you please advice what should be the way to go?

I have a webpack based project where I was using angular2-template-loader and angular2-router-loader to lazy load my feature bundles. Since i saw you used ngtools for AOT, i would like to use the feature but having issues with external templates being ignored.

**Comment by karptonite** [comment]
I just ran into this issue--the problem is that you need to install the html-loader with npm, and add a rule (loader) for handling html files to the webpack config.

**Comment by VivekPMenon** [comment]
Thanks @karptonite. I had figured it out later as and when i started using webpack for our builds, however missed out to update the issue...

**Comment by GiuseppePiscopo** [comment]
@VivekPMenon do you have an example project of your setup? We're having issues with current state of things on lazy routes + @ngtools/webpack + webpack, such that introducing a lazy loaded modules causes errors at compile time or runtime. Even with html-loader in place.

Currently trying with: 

* "webpack": "2.5.1",
* "typescript": "2.3.2",
* "@ngtools/webpack": "1.3.1",
* "@angular/compiler-cli": "4.1.1",

Thanks for any advice.
